Add the simplest test for submodules
Currently it fails with LFortran:

    $ lfortran submodule_03.f90
    Undefined symbols for architecture arm64:
      "___module_submodule_03_mod_f", referenced from:
          _main in a.out.tmp.o
    ld: symbol(s) not found for architecture arm64

The submodule is effectively ignored, so the interface to `f` does not
have an implementation.